### ISSUE TITLE
Joining without collateral to freeze the channel

### ISSUE THREAD

**Issue by jakub-wojciechowski** [PerunEthereum/Perun#3]
Hi guys, first congratulations on the excellent job of implementing the protocol :clap: :clap: :clap:

Currently, I'm analysing the simplest case without using VC.

I'm wondering about a scenario when: 
1) Alice initiates the channel and put some eth as a collateral
2) Bob joins the channel without any collateral
3) Bob is totally inactive
4) Alice cannot reclaim the invested money

I'm also thinking why the values initiated in the Party structs

`alice.cash = msg.value;`

and: 

`bob.cash = msg.value;`

are never used after being initially set.

Have you thought about this scenario or am I simply missing sth?

**Comment by MariusVanDerWijden** [comment]
Hey, about the first scenario your absolutely right. Thank you for noticing!
This is however just a bug in the implementation. We'll fix it as soon as we can.

Can you elaborate on the the values initiated with msg.value?

**Comment by jakub-wojciechowski** [comment]
Sorry, I cut off a fragment of my question while formatting the code. I meant that, the values, after being initially set, are never read.
I think it'd be a good idea to use the initial collaterals as constraints/requirements in accepting the signed messaged of state channel update (the sum of eth paid in == sum of proposed allocation) to prevent scenario of accidentally getting into a contract state where funds are frozen.

**Comment by MariusVanDerWijden** [comment]
Oh good point, I didn't develop the contracts so I haven't looked to deeply into them. 
What do you think about this?
https://github.com/PerunEthereum/Perun/tree/initialSig
It would give Alice the ability to close the channel, while still giving bob the chance to dispute with a valid signature of Alice

**Comment by MariusVanDerWijden** [comment]
Thank you for your input
